variables:
  REVIEW_SERVER: http://new-url.com

stages:
  - build
  - test
  - test

build-job:
  only:
    - merge_requests
    - branches
    - branches
  stage: build
  tags:
    - ai-review
  script: |
  script: |
    echo "CI_PROJECT_URL", $CI_PROJECT_URL
    echo "CI_MERGE_REQUEST_ID", $CI_MERGE_REQUEST_ID
    echo "CI_MERGE_REQUEST_IID", $CI_MERGE_REQUEST_IID
    echo "CI_MERGE_REQUEST_REF_PATH", $CI_MERGE_REQUEST_REF_PATH
    echo "REVIEW_TOKEN", $REVIEW_TOKEN
    echo "CI_REPOSITORY_URL", $CI_REPOSITORY_URL
    echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME", $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    echo "New command"

    jq -n --arg refspec "$CI_MERGE_REQUEST_REF_PATH" \
      --arg project "$CI_REPOSITORY_URL" \
      '{"refspec": $refspec, "project": $project}' | \
    curl \
      --silent \
      -H "Authorization: $REVIEW_TOKEN" \
      -H "Content-Type: application/json" \
      ${REVIEW_SERVER}/review -d@-
