variables:
  GITLAB_REFSPEC: "A global variable"

stages:
  - build

build-job:
  stage: build
  tags:
    - ai-review
  script: |
    echo "CI_PROJECT_URL", $CI_PROJECT_URL
    echo "CI_MERGE_REQUEST_IID", $CI_MERGE_REQUEST_IID

    jq -n --arg refspec "$GITLAB_REFSPEC" \
      --arg project "$CI_PROJECT_NAME" \
      '{"refspec": $refspec, "project": $project}'
