stages:
  - build

build-job:
  only:
    - merge_requests
  stage: build
  tags:
    - ai-review
  script: |
    echo "CI_PROJECT_URL", $CI_PROJECT_URL
    echo "CI_MERGE_REQUEST_ID", $CI_MERGE_REQUEST_ID
    echo "CI_MERGE_REQUEST_IID", $CI_MERGE_REQUEST_IID
    echo "CI_MERGE_REQUEST_REF_PATH", $CI_MERGE_REQUEST_REF_PATH
    echo "REVIEW_TOKEN", $REVIEW_TOKEN

    jq -n --arg refspec "$CI_MERGE_REQUEST_REF_PATH" \
      --arg project "$CI_PROJECT_NAME" \
      '{"refspec": $refspec, "project": $project}' | \
    curl \
      --silent \
      -H "Authorization: $REVIEW_TOKEN" \
      -H "Content-Type: application/json" \
      ${REVIEW_SERVER}/review -d@-
