variables:
  GITLAB_REFSPEC: "A global variable"

stages:
  - build

build-job:
  only:
    - merge_requests
  stage: build
  tags:
    - ai-review
  script: |
    echo "CI_PROJECT_URL", $CI_PROJECT_URL
    echo "CI_MERGE_REQUEST_ID", $CI_MERGE_REQUEST_ID
    echo "CI_MERGE_REQUEST_IID", $CI_MERGE_REQUEST_IID
    echo "CI_MERGE_REQUEST_REF_PATH", $CI_MERGE_REQUEST_REF_PATH

    jq -n --arg refspec "$GITLAB_REFSPEC" \
      --arg project "$CI_PROJECT_NAME" \
      '{"refspec": $refspec, "project": $project}'
