version: '2'

services:
  redis:
    image: redis:7.0.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      #command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - 'data:/data'

volumes:
  data: {}
