name: AI review

on:
  pull_request:

env: 
  GITHUB_REFSPEC: pull/${{ github.event.number }}/head:FETCH_HEAD
  REVIEW_SERVER: http://10.255.248.1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run review
        run: |
          curl --silent -H "Authorization: ${{ secrets.REVIEW_TOKEN }}" -H "Content-Type: application/json" http://10.255.248.1/review  -d '{"refspec": "refs/changes/63/125563/1", "project": "documentation-bot"}'

      # -d@-

      # jq -n --arg refspec "$GITHUB_REFSPEC" \
      #   --arg project "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
      #   '{"refspec": $refspec, "project": $project}' | \
      
      # - name: Extract all keywords from package.json
      #   uses: sergeysova/jq-action@v2
      #   id: keywords
      #   with:
      #     cmd: |
      #       jq -n --arg refspec "${GITHUB_REFSPEC}" \
      #             --arg project "${GITHUB_PROJECT_URL}" \
      #             --arg template "${shellEscape(TEMPLATE)}" \
      #             --arg model_name "${MODEL_NAME}" \
      #             '{"refspec": \$refspec, "project": \$project, "template": \$template, "model_name": \$model_name}'  |
      #       curl \
      #           --silent
      #           -H "Authorization: $REVIEW_TOKEN" \
      #           -H "Content-Type: application/json" \
      #           ${REVIEW_SERVER}/review -d@-
      #     multiline: true
      
      - name: Show keywords
        run: |
          keywords="${{ steps.keywords.outputs.value }}"
          for keyword in $keywords; do
            echo "$keyword"
          done

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
            ${{ steps.build.outputs.build-log }}

            Keywords:
            ${{ steps.keywords.outputs.value }}

            <test>
          edit-mode: replace